import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";
import "../css/Dashboard.css";

const Dashboard = () => {
  const { token } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { fetch("http://localhost:5000/api/crop-losses/summary", { headers: { Authorization: `Bearer ${token}` } }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.message); setData(body); }).catch((e) => setError(e.message)); }, [token]);
  const summary = data?.summary || { totalReports: 0, totalAffectedArea: 0, averageLossPercent: 0, mostAffectedCrop: null, percentOfBaselineAffected: null };
  return <main className="dashboard-page"><div className="dashboard-container"><section className="dashboard-header"><div><span className="dashboard-label">FARM OVERVIEW</span><h1>Dashboard</h1><p>Use your verified records to understand seasonal crop loss and prepare a claim.</p></div><Link to="/log-loss" className="dashboard-primary-button">+ Log Crop Loss</Link></section>
    {error && <div className="dashboard-notice"><p>{error}</p></div>}<section className="dashboard-stats">{[["📋", "Total reports", summary.totalReports, "Documented incidents"], ["📉", "Average crop loss", `${summary.averageLossPercent.toFixed(1)}%`, "Across all reports"], ["🌾", "Affected area", `${summary.totalAffectedArea.toFixed(1)} ac`, "Total recorded acreage"], ["🌱", "Most affected crop", summary.mostAffectedCrop || "—", summary.mostAffectedCrop ? "Based on report count" : "No incidents recorded"]].map(([icon, label, value, note]) => <div className="dashboard-stat-card" key={label}><div className="stat-icon">{icon}</div><div className="stat-content"><span className="stat-label">{label}</span><strong>{value}</strong><span className="stat-description">{note}</span></div></div>)}</section>
    <section className="dashboard-main-grid"><div className="dashboard-card loss-overview-card"><div className="dashboard-card-header"><div><h2>Seasonal claim position</h2><p>Recorded affected land compared with your farm baseline.</p></div></div><div className="farm-status-content"><div className="farm-status-icon">🛡️</div><h3>{data?.baseline ? `${summary.percentOfBaselineAffected?.toFixed(1)}% of baseline land affected` : "Set a farm baseline"}</h3><p>{data?.baseline ? `${summary.totalAffectedArea.toFixed(2)} of ${data.baseline.totalFarmSize} acres has been documented in loss reports.` : "Add your cultivated land and crops so CropShield can calculate the scale of loss."}</p><Link to="/farm-baseline" className="farm-status-button">{data?.baseline ? "View Farm Baseline" : "Set Farm Baseline"}</Link></div></div><div className="dashboard-card quick-actions-card"><div className="dashboard-card-header"><div><h2>Quick actions</h2><p>Keep your claim record current.</p></div></div><div className="quick-actions"><Link to="/log-loss" className="quick-action"><span className="quick-action-icon">📉</span><span><strong>Log Crop Loss</strong><small>Document a new incident</small></span><span className="action-arrow">→</span></Link><Link to="/reports" className="quick-action"><span className="quick-action-icon">📋</span><span><strong>Export Claim Summary</strong><small>Download all evidence details</small></span><span className="action-arrow">→</span></Link></div></div></section>
    <section className="dashboard-bottom-grid"><div className="dashboard-card recent-reports-card"><div className="dashboard-card-header"><div><h2>Recent reports</h2><p>Your latest documented incidents</p></div><Link to="/reports">View all</Link></div><div className="recent-reports-list">{data?.losses?.slice(0, 4).map((loss) => <div className="recent-report" key={loss._id}><div className="recent-report-icon">🌾</div><div className="recent-report-info"><strong>{loss.cropType}</strong><span>{loss.cause} · {new Date(loss.lossDate).toLocaleDateString()}</span></div><div className="recent-report-loss"><strong>{loss.estimatedLossPercent}%</strong><span>loss</span></div></div>)}{!data?.losses?.length && <p>No reports yet. Record a loss event as soon as possible for the strongest evidence.</p>}</div></div></section></div></main>;
};
export default Dashboard;
